name: Vite build test

on:
  push:
    branches:
      - dev

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Clear dependencies
        run: rm package-lock.json

      - name: Install dependencies
        run: npm i

      - name: Build
        run: npm run build
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
          aws-region: ap-northeast-2
          
      - name: Deploy To Dev S3
        run: aws s3 sync ./dist s3://${{ secrets.S3_DEV_BUCKET_NAME }}/